AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Root Stack for Slchess Backend

Parameters:
  StackName:
    Type: String
    Default: ludofy
  DeployJobImageUri:
    Type: String
  DeploymentStage:
    Type: String
    Default: dev

Resources:
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSBatchServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  ### Auth ###
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${StackName}-${DeploymentStage}-UserPool"
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${StackName}-${DeploymentStage}-UserPoolClient"
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "${StackName}-${DeploymentStage}"
      UserPoolId: !Ref UserPool

  ### BATCH JOB ###
  BatchComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: !Sub "${StackName}-ComputeEnv"
      Type: MANAGED
      ComputeResources:
        Type: FARGATE
        MaxvCpus: 256
        Subnets:
          - subnet-08afaaea0b1e4f825
          - subnet-0f7183aa53381f50c
          - subnet-0642049eeace8e1b3
        SecurityGroupIds:
          - sg-003fd8c2326289ec4
      ServiceRole: BatchServiceRole

  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironment
      Priority: 1

  BatchJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Sub "${StackName}-deploy-job-definition"
      Type: Container
      PlatformCapabilities:
        - FARGATE
      ContainerProperties:
        Image: !Ref DeployJobImageUri
        ResourceRequirements:
          - Type: VCPU
            Value: "1"
          - Type: MEMORY
            Value: "2048"
        ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECSTaskExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:GetAuthorizationToken
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: SSMParameterAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}/*"

  ### HTTP API Gateway ###
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "${StackName}-http-api"
      StageName: !Ref DeploymentStage
      FailOnWarnings: true
      CorsConfiguration:
        AllowOrigins: ["*"]
        AllowHeaders:
          - Authorization
          - Stripe-Signature
        AllowMethods:
          - GET
          - POST
          - DELETE
      Auth:
        Authorizers:
          CognitoAuthorizer:
            JwtConfiguration:
              issuer: !Sub
                - "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPoolId}"
                - UserPoolId: !Ref UserPool
              audience:
                - !Ref UserPoolClient
            IdentitySource: "$request.header.Authorization"
        DefaultAuthorizer: CognitoAuthorizer

  DeployBackend:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "${StackName}-${DeploymentStage}-DeployBackend"
      CodeUri: ./cmd/paas/deployBackend/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 10
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref StackName
        - Statement:
            - Effect: Allow
              Action:
                - batch:SubmitJob
              Resource: "*"
      Environment:
        Variables:
          MAIN_BUCKET_NAME: !Ref StackName
          BATCH_JOB_NAME: "deploy-backend"
          BATCH_JOB_QUEUE: !Ref BatchJobQueue
          BATCH_JOB_DEFINITION: !Ref BatchJobDefinition
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /deploy
            Method: POST
            ApiId: !Ref HttpApi

  ### Storage ###
  Deployments:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${StackName}-${DeploymentStage}-Deployments"
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: UserId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

Outputs:
  DeployBackendUrl:
    Description: "Endpoint URL for deploying backend"
    Value: !Sub "POST https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${DeploymentStage}/deploy"
