AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Root Stack for Slchess Backend

Parameters:
  StackName:
    Type: String
    Default: ludofy
  DeployJobImageUri:
    Type: String
  RemoveJobImageUri:
    Type: String
  DeploymentStage:
    Type: String
    Default: dev

Resources:
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSBatchServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  ### Auth ###
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${StackName}-${DeploymentStage}-UserPool"
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${StackName}-${DeploymentStage}-UserPoolClient"
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "${StackName}-${DeploymentStage}"
      UserPoolId: !Ref UserPool

  ### BATCH JOB ###
  BatchComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: !Sub "${StackName}-ComputeEnv"
      Type: MANAGED
      ComputeResources:
        Type: FARGATE
        MaxvCpus: 256
        Subnets:
          - subnet-08afaaea0b1e4f825
          - subnet-0f7183aa53381f50c
          - subnet-0642049eeace8e1b3
        SecurityGroupIds:
          - sg-003fd8c2326289ec4
      ServiceRole: BatchServiceRole

  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironment
      Priority: 1

  DeployJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Sub "${StackName}-deploy-job-definition"
      Type: Container
      PlatformCapabilities:
        - FARGATE
      ContainerProperties:
        Image: !Ref DeployJobImageUri
        ResourceRequirements:
          - Type: VCPU
            Value: "1"
          - Type: MEMORY
            Value: "4096"
        ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
        JobRoleArn: !GetAtt DeployJobRole.Arn
        NetworkConfiguration:
          AssignPublicIp: ENABLED

  RemoveJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Sub "${StackName}-remove-job-definition"
      Type: Container
      PlatformCapabilities:
        - FARGATE
      ContainerProperties:
        Image: !Ref RemoveJobImageUri
        ResourceRequirements:
          - Type: VCPU
            Value: "0.25"
          - Type: MEMORY
            Value: "512"
        ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
        JobRoleArn: !GetAtt DeployJobRole.Arn
        NetworkConfiguration:
          AssignPublicIp: ENABLED

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECSTaskExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:GetAuthorizationToken
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: SSMParameterAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}/*"

  DeployJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DeployJobRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DeployJobPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:DetachRolePolicy
                  - iam:DeleteRolePolicy
                Resource: "arn:aws:iam::*:role/*"

              - Effect: Allow
                Action:
                  - cloudformation:*
                  - s3:*
                  - iam:*
                  - cognito-idp:*
                  - lambda:*
                  - dynamodb:*
                  - appsync:*
                  - logs:*
                  - apigateway:*
                  - batch:*
                  - events:*
                  - states:*
                  - secretsmanager:GetSecretValue
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ecs:*
                  - application-autoscaling:*
                Resource: "*"

  PostBackendDeployRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${StackName}-PostBackendDeployRule"
      EventPattern:
        source:
          - aws.batch
        detail-type:
          - Deploy Job State Change
        detail:
          status:
            - SUCCEEDED
            - FAILED
          jobName:
            - backend-deploy-job
      Targets:
        - Arn: !GetAtt PostBackendDeployFunction.Arn
          Id: PostBackendDeployTarget
          InputTransformer:
            InputPathsMap:
              jobName: "$.detail.jobName"
              jobId: "$.detail.jobId"
              jobQueue: "$.detail.jobQueue"
              status: "$.detail.status"
            InputTemplate: |
              {
                "jobName": "<jobName>",
                "jobId": "<jobId>",
                "jobQueue": "<jobQueue>",
                "status": "<status>"
              }

  PostBackendRemoveRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${StackName}-PostBackendRemoveRule"
      EventPattern:
        source:
          - aws.batch
        detail-type:
          - Remove Job State Change
        detail:
          status:
            - SUCCEEDED
            - FAILED
          jobName:
            - backend-remove-job
      Targets:
        - Arn: !GetAtt PostBackendRemoveFunction.Arn
          Id: PostBackendRemoveTarget
          InputTransformer:
            InputPathsMap:
              jobName: "$.detail.jobName"
              jobId: "$.detail.jobId"
              jobQueue: "$.detail.jobQueue"
              status: "$.detail.status"
            InputTemplate: |
              {
                "jobName": "<jobName>",
                "jobId": "<jobId>",
                "jobQueue": "<jobQueue>",
                "status": "<status>"
              }

  PermissionForEventsToInvokePostDeploy:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt PostBackendDeployFunction.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt PostBackendDeployRule.Arn

  PermissionForEventsToInvokePostRemove:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt PostBackendRemoveFunction.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt PostBackendRemoveRule.Arn

  ### HTTP API Gateway ###
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "${StackName}-http-api"
      StageName: !Ref DeploymentStage
      FailOnWarnings: true
      CorsConfiguration:
        AllowOrigins: ["*"]
        AllowHeaders:
          - Authorization
          - Content-Type
        AllowMethods:
          - GET
          - POST
          - DELETE
      Auth:
        Authorizers:
          CognitoAuthorizer:
            JwtConfiguration:
              issuer: !Sub
                - "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPoolId}"
                - UserPoolId: !Ref UserPool
              audience:
                - !Ref UserPoolClient
            IdentitySource: "$request.header.Authorization"
        DefaultAuthorizer: CognitoAuthorizer

  BackendDeployFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "${StackName}-${DeploymentStage}-BackendDeploy"
      CodeUri: ./cmd/paas/backendDeploy/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 10
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref StackName
        - Statement:
            - Effect: Allow
              Action:
                - batch:SubmitJob
                - batch:TagResource
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:CreateSecret
                - secretsmanager:UpdateSecret
                - secretsmanager:PutSecretValue
                - secretsmanager:TagResource
                - secretsmanager:DescribeSecret
              Resource: "*"
        - DynamoDBCrudPolicy:
            TableName: !Ref Deployments
        - DynamoDBCrudPolicy:
            TableName: !Ref Backends
      Environment:
        Variables:
          MAIN_BUCKET_NAME: !Ref StackName
          BATCH_JOB_NAME: "backend-deploy-job"
          BATCH_JOB_QUEUE: !Ref BatchJobQueue
          BATCH_JOB_DEFINITION: !Ref BatchJobDefinition
          DEPLOYMENTS_TABLE_NAME: !Ref Deployments
          BACKENDS_TABLE_NAME: !Ref Backends
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /deploy
            Method: POST
            ApiId: !Ref HttpApi

  PostBackendDeployFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "${StackName}-${DeploymentStage}-PostBackendDeploy"
      CodeUri: ./cmd/paas/postBackendDeploy/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Deployments
        - DynamoDBCrudPolicy:
            TableName: !Ref Backends
        - Statement:
            - Effect: Allow
              Action:
                - batch:DescribeJobs
              Resource: "*"
      Environment:
        Variables:
          DEPLOYMENTS_TABLE_NAME: !Ref Deployments
          BACKENDS_TABLE_NAME: !Ref Backends

  BackendRemoveFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "${StackName}-${DeploymentStage}-BackendRemove"
      CodeUri: ./cmd/paas/backendRemove/
      Handler: bootstrap
      Runtime: provided.al2023
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Backends
        - Statement:
            - Effect: Allow
              Action:
                - batch:SubmitJob
                - batch:TagResource
              Resource: "*"
      Environment:
        Variables:
          BATCH_JOB_NAME: "backend-remove-job"
          BATCH_JOB_QUEUE: !Ref BatchJobQueue
          BATCH_JOB_DEFINITION: !Ref BatchJobDefinition
          BACKENDS_TABLE_NAME: !Ref Backends
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /backend/{id}
            Method: DELETE
            ApiId: !Ref HttpApi

  BackendGetFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "${StackName}-${DeploymentStage}-BackendGet"
      CodeUri: ./cmd/paas/backendGet/
      Handler: bootstrap
      Runtime: provided.al2023
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Backends
        - CloudFormationDescribeStacksPolicy: {}
      Environment:
        Variables:
          BACKENDS_TABLE_NAME: !Ref Backends
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /backend/{id}
            Method: GET
            ApiId: !Ref HttpApi

  BackendListFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "${StackName}-${DeploymentStage}-BackendList"
      CodeUri: ./cmd/paas/backendList/
      Handler: bootstrap
      Runtime: provided.al2023
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Backends
      Environment:
        Variables:
          BACKENDS_TABLE_NAME: !Ref Backends
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /backends
            Method: GET
            ApiId: !Ref HttpApi

  DeploymentGetFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "${StackName}-${DeploymentStage}-DeploymentGet"
      CodeUri: ./cmd/paas/deploymentGet/
      Handler: bootstrap
      Runtime: provided.al2023
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Deployments
      Environment:
        Variables:
          DEPLOYMENTS_TABLE_NAME: !Ref Deployments
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /deployment/{id}
            Method: GET
            ApiId: !Ref HttpApi

  DeploymentListFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "${StackName}-${DeploymentStage}-DeploymentList"
      CodeUri: ./cmd/paas/deploymentList/
      Handler: bootstrap
      Runtime: provided.al2023
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Deployments
      Environment:
        Variables:
          DEPLOYMENTS_TABLE_NAME: !Ref Deployments
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /deployments
            Method: GET
            ApiId: !Ref HttpApi

  ### Storage ###
  Backends:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${StackName}-${DeploymentStage}-Backends"
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: UserId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  Deployments:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${StackName}-${DeploymentStage}-Deployments"
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: UserId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

Outputs:
  BackendDeployUrl:
    Description: "Endpoint URL for deploying backend"
    Value: !Sub "POST https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${DeploymentStage}/deploy"

  BackendRemoveUrl:
    Description: "Endpoint URL for removing backend"
    Value: !Sub "DELETE https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${DeploymentStage}/backend/{id}"

  BackendGetUrl:
    Description: "Endpoint URL for getting backend information"
    Value: !Sub "GET https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${DeploymentStage}/backend/{id}"

  BackendListUrl:
    Description: "Endpoint URL for listing backends of a user"
    Value: !Sub "GET https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${DeploymentStage}/backends"

  DeploymentGetUrl:
    Description: "Endpoint URL for getting deployment information"
    Value: !Sub "GET https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${DeploymentStage}/deployment/{id}"

  DeploymentListUrl:
    Description: "Endpoint URL for listing deployments of a user"
    Value: !Sub "GET https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${DeploymentStage}/deployments"
