AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Customization Stack

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Architectures:
      - arm64

Parameters:
  StackName:
    Type: String
  DeploymentStage:
    Type: String

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: HelloWorldFunction
      Handler: bootstrap
      Runtime: provided.al2023
      InlineCode: |
        package main

        import (
          "context"
          "net/http"

          "github.com/aws/aws-lambda-go/events"
          "github.com/aws/aws-lambda-go/lambda"
        )

        func handler(
        	ctx context.Context,
        	event events.APIGatewayProxyRequest,
        ) (
        	events.APIGatewayProxyResponse,
          error,
        ) {
            return events.APIGatewayProxyResponse{
                StatusCode: http.StatusOK,
                Body:       "Hello World!",
          	}, nil
        }

        func main() {
            lambda.Start(handler)
        }

  HelloWorldIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Fn::ImportValue: !Sub "${StackName}-HttpApiId"
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt HelloWorldFunction.Arn
      PayloadFormatVersion: "2.0"

  HelloWorldRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Fn::ImportValue: !Sub "${StackName}-HttpApiId"
      RouteKey: GET /helloWorld
      Target: !Sub
        - integrations/${IntegrationId}
        - IntegrationId: !Ref HelloWorldIntegration

Outputs:
  HelloWorldEndpointUrl:
    Value: !Sub
      - "GET ${HttpApiEndpoint}/helloWorld"
      - HttpApiEndpoint:
          Fn::ImportValue: !Sub "${StackName}-HttpApiEndpoint"
