AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Customization Stack

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Architectures:
      - arm64

Parameters:
  StackName:
    Type: String
  DeploymentStage:
    Type: String

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: nodejs20.x
    Properties:
      FunctionName: !Sub "${StackName}-${DeploymentStage}-HelloWorldFunction"
      Runtime: nodejs20.x
      Handler: index.handler
      InlineCode: |
        exports.handler = async (event) => {
          return {
            statusCode: 200,
            body: "Hello World!",
          };
        };

  HelloWorldIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Fn::ImportValue: !Sub "${StackName}-HttpApiId"
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
      PayloadFormatVersion: "2.0"

  HelloWorldRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Fn::ImportValue: !Sub "${StackName}-HttpApiId"
      RouteKey: GET /helloWorld
      Target: !Sub
        - integrations/${IntegrationId}
        - IntegrationId: !Ref HelloWorldIntegration

  HelloWorldLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt HelloWorldFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApiId}/*/*/helloWorld
        - HttpApiId:
            Fn::ImportValue: !Sub "${StackName}-HttpApiId"

Outputs:
  HelloWorldEndpointUrl:
    Value: !Sub
      - "GET ${HttpApiEndpoint}/helloWorld"
      - HttpApiEndpoint:
          Fn::ImportValue: !Sub "${StackName}-HttpApiEndpoint"
