version: "3"

env:
  AWS_SAM_DIR: .aws-sam
  BUILD_DIR: "{{.AWS_SAM_DIR}}/build"
  STACK: slchess

includes:
  utils:
    taskfile: ./Util.yml
    internal: true
    dir: ../

tasks:
  output:
    desc: Print stack output to json file
    cmds:
      - sam list stack-outputs --stack-name slchess --output json

  deploy:
    desc: Deploy the current local stack on AWS
    deps: [utils:check-base-env]
    cmds:
      - sam build --region $AWS_REGION --config-file samconfig.yaml
      - sam deploy
        --stack-name $STACK
        --region $AWS_REGION
        --parameter-overrides "ServerImageUri=$SERVER_IMAGE_URI StofinetImageUri=$STOFINET_IMAGE_URI"
        --confirm-changeset
        --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
        --on-failure DELETE
        --config-file samconfig.yaml
        --config-env default

  remove:
    desc: Remove the stack from AWS
    deps: [utils:check-base-env]
    cmds:
      - sam delete --region $AWS_REGION --config-file samconfig.yaml
      - rm ./configs/aws/*.env
      - rm -rf ./.aws-sam

  sync:
    desc: Sync the stack
    cmds:
      - sam sync --stack-name $STACK --watch

  build:
    desc: Build the stack
    deps: [utils:check-base-env]
    vars:
    cmds:
      - sam build --region $AWS_REGION --config-file samconfig.yaml --no-cached
